# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      homepage.name: "pgadmin16"
      homepage.href: "http://zoonas.i234.me:8086/"
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"
      homepage.group: "Web"
      homepage.description: "Postgres administration web UI"
      homepage.icon: "postgres"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
      
  db_net:
    aliases:
      - postgres16

# The main Docker Compose file
services:
  postgres16:
    container_name: postgres16
    user: "1029:100"
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "basync"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: on-failure:5
    volumes:
      - "/volume1/docker/postgres16/config/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "/volume1/docker/postgres16/data:/var/lib/postgresql/data"
    environment:
      - "TZ=Europe/Zurich"
      - "POSTGRES_USER=${POSTGRES_USER_ENV}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}"
    command:
      [
        'postgres',
        '-c',
        'shared_preload_libraries=vectors.so',
        '-c',
        'search_path="$$user", public, vectors',
        '-c',
        'logging_collector=on',
        '-c',
        'max_wal_size=2GB',
        '-c',
        'shared_buffers=512MB',
        '-c',
        'wal_compression=on',
      ]      
    networks: *base_networks

  pgadmin16:
    image: "dpage/pgadmin4:latest"
    container_name: "pgadmin16"
    user: "1029:100"
    healthcheck:
      test: ["CMD", "wget", "-O", "-", "http://localhost:80/misc/ping"]
      interval: 300s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: on-failure:5
    ports:
      - 8086:80    
    volumes:
      - "/volume1/docker/postgres16/pgadmin-data:/var/lib/pgadmin"
      - "/volume1/docker/postgres16/log:/var/log"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL_ENV}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD_ENV}"
    labels: *base_labels
    networks: *base_networks


networks:
  # Access the db-network
  db_net:
    name: db_network
    external: true
