#
# Ansible managed
#

# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      traefik.enable: "true"
      traefik.docker.network: "traefik_network"
      traefik.http.services.traefik.loadbalancer.server.port: "8080"
      traefik.http.routers.traefik_web.EntryPoints: "web-secure"
      traefik.http.routers.traefik_web.rule: "Host(`traefik.kite-gila.work`)"
      traefik.http.routers.traefik_web.service: "traefik"
      traefik.http.routers.traefik_web.tls: true
      traefik.http.routers.traefik_web.tls.certresolver: "default"
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
  
  traefik_net:
    aliases:
      - traefik
      

# The main Docker Compose file
services:
  traefik:
    image: traefik:2.11.16
    container_name: "traefik"
    restart: always
    healthcheck:
      test: "traefik healthcheck"
    ports:
      - "80:80"
      - "443:443"
    environment:
      PUID: "1000"
      PGID: "1002"
      TZ: "Europe/Berlin"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/volume1/docker/traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
      - "/volume1/docker/traefik/dynamic:/etc/traefik/dynamic"
      - "/volume1/docker/traefik/acme.json:/etc/traefik/acme/acme.json:rw"
    labels:
      << : *base_labels
      traefik.http.middlewares.traefik_web-auth.basicauth.users: "admin:$$apr1$$C7q4MwxW$$3DbS4TuKkgnkPvS8H3vZG1"
      traefik.http.routers.traefik_web.middlewares: "traefik_web-auth"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: *base_networks

networks:
  # Access the traefik-network
  traefik_net:
    name: traefik_network
    external: true
