# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
      
  db_net:
    aliases:
      - immich

# The main Docker Compose file
services:
  immich:
    image: ghcr.io/immich-app/immich-server:release
    container_name: "immich"
    hostname: immich
    user: 1029:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - immich.env
    ports:
      - 2283:2283
    volumes:
      - "/volume1/docker/immich/upload:/usr/src/app/upload:rw"
      - "/volume1/docker/sftpgo/data/home/minda/photo:/usr/src/app/external:rw"
    restart: on-failure:5
    labels: *base_labels
    networks: *base_networks

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:release
    container_name: Immich-LEARNING
    hostname: immich-machine-learning
    user: 1029:100
    security_opt:
      - no-new-privileges:true
    env_file:
      - immich.env
    volumes:
      - "/volume1/docker/immich/cache:/cache:rw"
    restart: on-failure:5
    networks: *base_networks

  immich-folder-album-creator:
    container_name: immich_folder_album_creator
    image: salvoxia/immich-folder-album-creator:latest
    restart: unless-stopped
    environment:
      API_URL: http://zoonas.i234.me:2283/api
      API_KEY: ${API_KEY_ENV}
      ROOT_PATH: /usr/src/app/external
      ALBUM_LEVELS: 2
      SET_ALBUM_THUMBNAIL: first
      UNATTENDED: "1"
      CRON_EXPRESSION: "5 1 * * *"
      TZ: Europe/Zurich        

networks:
  # Access the db-network
  db_net:
    name: db_network
    external: true
