# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"
      homepage.group: "Media"
      homepage.description: "Jellyfin media server"
      homepage.icon: "jellyfin"
      homepage.name: "jellyfin"
      homepage.href:"https://jellyfin.zoonas.i234.me/"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
      

# The main Docker Compose file
services:
  jellyfin:
    image: "jellyfin/jellyfin:latest"
    container_name: "jellyfin"
    user: 1029:100
    mem_limit: 4g
    cpu_shares: 1024
    environment:
      TZ: "Europe/Zurich"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8096' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    ports:
      - 8096:8096          
    volumes:
      - "/volume1/docker/jellyfin/config:/config:rw"
      - "/volume1/docker/jellyfin/cache:/cache:rw"
      - "/volume1/docker/jellyfin/logs:/logs:rw"
      - "/volume1/video:/media:rw"
#      - "/volume1/music:/music:rw"
    restart: on-failure:5
    labels: *base_labels
    networks: *base_networks




