# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
      
  db_net:
    aliases:
      - freshrss

# The main Docker Compose file
services:
  freshrss:
    image: "ghcr.io/linuxserver/freshrss:1.24.3"
    container_name: "freshrss"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:80"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s      
    restart: on-failure:5
    logging:
      options:
        max-size: 10m
    environment:
      TZ: Europe/Zurich
      CRON_MIN: 3,33
      PUID: 1029 
      PGID: 100 
      BASE_URL: "https://rss.zoonas.i234.me"
      SERVER_DNS: "rss.zoonas.i234.me"
      ADMIN_EMAIL: ${ADMIN_EMAIL_ENV}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD_ENV}
      ADMIN_API_PASSWORD: ${ADMIN_API_PASSWORD_ENV}
      TRUSTED_PROXY: 100.64.0.0/10
      DB_HOST: postgres16:5432
      DB_BASE: freshrss
      DB_USER: freshrss_user
      DB_PASSWORD: ${DB_PASSWORD_ENV}
    volumes:
      - "/volume1/docker/freshrss/config:/config:rw"
    
    labels: *base_labels
    networks: *base_networks      



networks:
  # Access the db-network
  db_net:
    name: db_network
    external: true
