# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      homepage.name: "redis7"
      homepage.href: "https://redis-commander.zoonas.i234.me/"
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"
      homepage.group: "Web"
      homepage.description: "Redis commander web UI"
      homepage.icon: "redis"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
      
  db_net:
    aliases:
      - redis7

# The main Docker Compose file
services:
  redis7:
    image: redis:7
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD_ENV}    
    container_name: redis7
    mem_limit: 512m
    mem_reservation: 256m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: "1029:100"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - "/volume1/docker/redis7/data:/data:rw"
    environment:
      - TZ="Europe/Zurich"
    restart: on-failure:5
    networks: *base_networks    

  # rediscommander:
    # container_name: rediscommander
    # image: ghcr.io/joeferner/redis-commander:latest
    # restart: on-failure:5
    # depends_on:
      # redis7:
        # condition: service_healthy
    # environment:
    # - REDIS_HOST=redis7
    # - REDIS_PORT=6379
    # - REDIS_PASSWORD=${REDIS_PASSWORD_ENV}
    # - HTTP_USER=${HTTP_USER_ENV}
    # - HTTP_PASSWORD=${HTTP_PASSWORD_ENV}

    # ports:
    # - "8081:8081"
    # labels: *base_labels
    # networks: *base_networks

networks:
  # Access the db-network
  db_net:
    name: db_network
    external: true
