---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Storage:
    - zoonas:
        - abbr: SP
          icon: synology-dsm
          href: https://zoonas.i234.me/

- Deploy:
    - home.kite-gila:
        - abbr: KG
          icon: homepage
          href: https://home.kite-gila.work/
    - home.zoonas.i234.me:
        - abbr: ZN
          icon: synology
          href: https://home.zoonas.i234.me/          

- Security:
    - vaultwarden:
        - abbr: VW
          icon: bitwarden
          href: https://vaultwarden.zoonas.i234.me/
