# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
      
  db_net:
    aliases:
      - pgbackweb

# The main Docker Compose file
services:
  pgbackweb:
    image: eduardolat/pgbackweb:latest
    container_name: pgbackweb
    user: "1029:100"
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8085' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    restart: on-failure:5
    ports:
      - 8095:8085
    environment:
      - "TZ=Europe/Zurich"
      - "PBW_ENCRYPTION_KEY=${PBW_ENCRYPTION_KEY_ENV}"
      - "PBW_POSTGRES_CONN_STRING=${PBW_POSTGRES_CONN_STRING_ENV}"      
    volumes:
      - "/volume1/docker/backup:/backups:rw"
    labels: *base_labels
    networks: *base_networks

networks:
  # Access the db-network
  db_net:
    name: db_network
    external: true
