# Labels for Traefik, Watchtower, and Autoheal
#   (docker compose ignores fields that start with `x-`. So we can use them to
#    define reusable fragments with `&anchors`. See:
#    https://docs.docker.com/compose/compose-file/11-extension/ )
x-labels: &base_labels
      homepage.name: "inbucket"
      homepage.href: "https://webmail.zoonas.i234.me/"
      com.centurylinklabs.watchtower.enable: "true"
      autoheal: "true"
      homepage.group: "Services"
      homepage.description: "Disposable webmail service"
      homepage.icon: "docker-mailserver"

# Reusable default networks configuration to ensure container is part of both
# the traefik network and the default network of this compose file
x-networks: &base_networks
  default:
      

# The main Docker Compose file
services:
  inbucket:
    container_name: "inbucket"
    image: "inbucket/inbucket:latest"   
    restart: unless-stopped
    ports: # Ports: Webmail, SMTP, POP3
      - 8088:9000
      - 2500:2500
      - 1100:1100
    volumes:
      - "/volume1/docker/inbucket/config:/config"
      - "/volume1/docker/inbucket/storage:/storage"
    environment:
      - "INBUCKET_WEB_BASEPATH=zoonas.i234.me"
    labels: *base_labels